spring:
  profiles:
    include:
      - db
      - papago
  datasource:
    url: ${CLEARDB_DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa: #
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

papago:
  clientId: ${PAPAGO_CLIENT_ID}
  clientSecret: ${PAPAGO_CLIENT_SECRET}
  apiURL: ${PAPAGO_API_URL}

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

  logging:
    level:
      me.silvernine: DEBUG

